
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/



#include <iostream>
#include <stdlib.h>
#include <time.h>
#include <math.h>
#include <string>
using namespace std;


int main()
{

//Fibonacci Sequence
int fibNum = 1;
int stor = 0;

for(int i = 1; fibNum <= 4000000;){

  int preNum = fibNum;
  if (fibNum % 2 == 0) {
    cout << fibNum << endl;
     stor += fibNum;
  }
  fibNum += i;


  i = preNum;

}

cout << "The sum is: " << stor << endl;

}
/*
int temp = stable;
stable += i;
i = temp;
cout << stable << endl;
*/
